import Head from 'next/head'
import { ReactNode } from 'react'
import { NextComponentType } from 'next'
import { ThemeProvider } from 'next-themes'
import 'react-toastify/dist/ReactToastify.css'
import { ApolloProvider } from '@apollo/client'
import { ToastContainer } from 'react-toastify'
import type { AppContext, AppInitialProps, AppLayoutProps } from 'next/app'
import DappProvider from '../utils/ethers/DappProvider'
import Header from '../components/Header'
import { client } from '../apollo/client'
import '../styles/globals.css'

const MyApp: NextComponentType<AppContext, AppInitialProps, AppLayoutProps> = ({
  Component,
  pageProps,
}: AppLayoutProps) => {
  const getLayout = Component.getLayout || ((page: ReactNode) => page)
  const AnyComponent = Component as any
  return (
    <ThemeProvider enableSystem={true} attribute="class">
      <ApolloProvider client={client}>
        <DappProvider>
          <Head>
            <title>COMMISSIONER</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          {getLayout(<AnyComponent {...pageProps} />)}
        </DappProvider>
      </ApolloProvider>
      <ToastContainer position="bottom-right" />
    </ThemeProvider>
  )
}

export default MyApp
